version: '3.1'
services:
    app:
        container_name: alpha
        image: alpha
        build: ./
        ports:
         - "8080:8080"
        depends_on:
         - postgresqldb
        environment:
         - SPRING_DATASOURCE_PASSWORD=postgres
         - SPRING_DATASOURCE_USERNAME=postgres
         - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/alphadb
    postgresqldb:
        image: postgres
        ports:
         - "5432:5432"
        environment:
         - POSTGRES_DB=alphadb
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres